### ISSUE TITLE
not working on Fedora 30 since the latest update

### ISSUE THREAD

**Issue by QQQNo** [mkrajnak/shutdown-timer-gnome-shell-extension#5]
It worked fine until just now, installed the latest update via gnome extensions and now it won't work at all, simply returns ERROR in gnome extensions.

When clicking on settings it gives the following error message:
```
The settings of extension shutdown-timer-gnome-shell-extension had an error:
```
Error: Schema org.gnome.shell.extensions.automatic-shutdown-timer could not be found for extension shutdown-timer-gnome-shell-extension. Please check your installation.
```

Stack trace:
```
getSettings@/home/USERNAME/.local/share/gnome-shell/extensions/shutdown-timer-gnome-shell-extension/convenience.js:25:15
init@/home/USERNAME/.local/share/gnome-shell/extensions/shutdown-timer-gnome-shell-extension/prefs.js:27:14
_getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:60:9
_selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:74:31
_onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
@<main>:1:43
```
```

**Comment by mkrajnak** [comment]
Thanks for issue, I will activate the older version in extension page for now and investigate what went wrong.

**Comment by mkrajnak** [comment]
Posted new version for a review, thanks again

**Comment by mkrajnak** [comment]
Version was approved, tested on GNOME 3.32, thanks again
