### ISSUE TITLE
Not working in Gnome 40 

### ISSUE THREAD

**Issue by QQQNo** [mkrajnak/shutdown-timer-gnome-shell-extension#8]
Hello,

unfortunately, this extension isn't working in Gnome 40 anymore. It shows up as Outdated in Gnome Extensions. Tested in Fedora 34.

Thanks for your time!

**Comment by mkrajnak** [comment]
Hi, thanks to @aaitmouloud we have a GNOME40 version merged and submitted to GNOME extension site for a review, hopefully it will be available soon :)
