### ISSUE TITLE
Timer resumes after re-enable the extension

### ISSUE THREAD

**Issue by auipga** [mkrajnak/shutdown-timer-gnome-shell-extension#9]
Better behavior would be to pause when the extension is disabled.

**Comment by mkrajnak** [comment]
Hi, I'm not sure If I understand what you mean by re-enabling extension.
What I quickly tested was:
 1. Starting the timer
 2. Disabling the extension through Extension app
 3. Enabling it back
And the timer is paused. If you meant something different  please described what steps needs to be executed to expose the issue. Thanks !

**Comment by auipga** [comment]
You understood correctly.
My system powered off a few seconds after I re-enabled the extension (with a running timer at the time of disabling).

I tested again with all scenarios I could think of but **can not reproduce**. Closing. Sorry.
